# Generated by Django 3.1.5 on 2021-01-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atrações'},
        ),
    ]
